# Generated by Django 3.0.6 on 2020-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
