# Generated by Django 3.0.6 on 2020-06-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0002_seller_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
