# Generated by Django 3.0.6 on 2020-06-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0003_auto_20200602_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='city',
        ),
    ]
