# Generated by Django 3.0.6 on 2020-06-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0004_auto_20200604_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_details',
            new_name='seller_name',
        ),
    ]
