# Generated by Django 3.0.6 on 2020-06-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0009_auto_20200605_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
