# Generated by Django 3.0.6 on 2020-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0014_auto_20200623_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
