# Generated by Django 3.0.6 on 2020-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0015_auto_20200623_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
