# Generated by Django 3.0.6 on 2020-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0017_auto_20200623_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
