# Generated by Django 3.0.6 on 2020-06-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0020_auto_20200623_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
    ]
