# Generated by Django 3.0.6 on 2020-06-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0021_remove_seller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
