# Generated by Django 3.0.6 on 2020-06-23 13:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0022_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
