# Generated by Django 3.0.6 on 2020-06-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0024_auto_20200623_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
